import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Loader2,MessageSquareMore,RefreshCw,Send,X} from 'lucide-react';
import {cancelPDDMessage,confirmPDDMessage,createPDDMessage,getPDDMessages,PDDMessageTask,retryPDDMessage} from '../services/api';

const labels:Record<string,string>={pending:'待预检',preflighting:'正在预检',awaiting_confirmation:'待人工确认',confirmed:'已确认待发送',sending:'正在发送',verified:'已发送',result_unknown:'结果待核验',failed:'失败',cancelled:'已取消'};
const fmt=(v:number)=>v?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v*1000)):'-';
const PDDMessageWorkbench:React.FC=()=>{
 const [rows,setRows]=useState<PDDMessageTask[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState('');
 const [form,setForm]=useState({goods_id:'',sku_id:'',mall_sn:'',pdd_order_id:'',task_type:'custom_message',message:''});
 const load=async()=>{setLoading(true);try{setRows(await getPDDMessages(filter));setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[filter]);
 const counts=useMemo(()=>({confirm:rows.filter(x=>x.status==='awaiting_confirmation').length,unknown:rows.filter(x=>x.status==='result_unknown').length}),[rows]);
 const create=async()=>{if(!form.goods_id.trim()||!form.message.trim()){setError('请填写 goods_id 和消息正文');return}setBusy('create');try{const key=`manual-message:${form.goods_id}:${Date.now()}`;await createPDDMessage({...form,send_mode:'manual_confirm'},key);setOpen(false);setForm({goods_id:'',sku_id:'',mall_sn:'',pdd_order_id:'',task_type:'custom_message',message:''});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const confirm=async(row:PDDMessageTask)=>{if(!window.confirm('确认向该拼多多商家发送此消息？确认后正文不可修改。'))return;setBusy(row.id);try{await confirmPDDMessage(row.id);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const cancel=async(row:PDDMessageTask)=>{setBusy(row.id);try{await cancelPDDMessage(row.id);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const retry=async(row:PDDMessageTask)=>{setBusy(row.id);try{await retryPDDMessage(row.id);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 return <div className="space-y-6 animate-fade-in">
  <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-600 text-white"><MessageSquareMore/></div><div><h1 className="text-3xl font-black">拼多多消息</h1><p className="mt-1 text-sm text-gray-500">商家聊天预检、人工确认、发送验证与审计</p></div></div><div className="flex gap-2"><button onClick={load} className="rounded-xl bg-gray-100 px-4 py-2.5 font-bold"><RefreshCw className="mr-2 inline h-4 w-4"/>刷新</button><button onClick={()=>setOpen(true)} className="rounded-xl bg-violet-600 px-4 py-2.5 font-bold text-white">新建消息</button></div></div>
  <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="mr-2 inline h-4 w-4"/>默认人工确认。真实发送还必须在系统设置开启安全开关；结果未知时禁止盲目重发。</div>
  {error&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-5 shadow-sm"><div className="text-xs font-bold text-gray-400">待人工确认</div><div className="mt-2 text-3xl font-black text-amber-600">{counts.confirm}</div></div><div className="rounded-xl bg-white p-5 shadow-sm"><div className="text-xs font-bold text-gray-400">结果待核验</div><div className="mt-2 text-3xl font-black text-red-600">{counts.unknown}</div></div></div>
  <div className="flex flex-wrap gap-2">{Object.entries({'':'全部',pending:'待预检',awaiting_confirmation:'待确认',confirmed:'待发送',result_unknown:'待核验',failed:'失败',verified:'已发送'}).map(([k,v])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filter===k?'bg-violet-600 text-white':'border bg-white'}`}>{v}</button>)}</div>
  <div className="overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center p-16"><Loader2 className="animate-spin"/></div>:rows.length===0?<div className="p-16 text-center text-gray-400">暂无消息任务</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-4">任务</th><th className="p-4">商品/订单</th><th className="p-4">消息</th><th className="p-4">状态</th><th className="p-4"></th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t align-top"><td className="p-4"><div className="font-bold">{row.task_type}</div><div className="mt-1 text-xs text-gray-400">{fmt(row.created_at)} · 尝试 {row.attempts}</div></td><td className="p-4 font-mono text-xs"><div>goods {row.goods_id}</div><div>sku {row.sku_id||'-'}</div><div>订单 {row.pdd_order_id||'-'}</div></td><td className="max-w-md whitespace-pre-wrap p-4 text-gray-700">{row.message}</td><td className="p-4"><span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${row.status==='verified'?'bg-green-50 text-green-700':row.status==='result_unknown'||row.status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{labels[row.status]||row.status}</span>{row.last_error&&<div className="mt-2 text-xs text-red-600">{row.last_error}</div>}</td><td className="p-4"><div className="flex gap-2">{row.status==='awaiting_confirmation'&&<button disabled={busy===row.id} onClick={()=>confirm(row)} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white"><Send className="mr-1 inline h-3.5 w-3.5"/>确认发送</button>}{row.status==='failed'&&<button disabled={busy===row.id} onClick={()=>retry(row)} className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">重试</button>}{['pending','awaiting_confirmation','failed'].includes(row.status)&&<button disabled={busy===row.id} onClick={()=>cancel(row)} className="rounded-lg bg-gray-100 px-3 py-2 text-xs font-bold">取消</button>}{row.status==='verified'&&<CheckCircle2 className="text-green-600"/>}</div></td></tr>)}</tbody></table></div>}</div>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black">新建拼多多商家消息</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="space-y-4 p-5"><div className="grid gap-3 sm:grid-cols-2"><input className="ios-input rounded-xl px-4 py-3" placeholder="goods_id *" value={form.goods_id} onChange={e=>setForm({...form,goods_id:e.target.value})}/><input className="ios-input rounded-xl px-4 py-3" placeholder="sku_id（可选）" value={form.sku_id} onChange={e=>setForm({...form,sku_id:e.target.value})}/><input className="ios-input rounded-xl px-4 py-3" placeholder="mall_sn（留空从采集数据读取）" value={form.mall_sn} onChange={e=>setForm({...form,mall_sn:e.target.value})}/><input className="ios-input rounded-xl px-4 py-3" placeholder="拼多多订单号（订单消息必填）" value={form.pdd_order_id} onChange={e=>setForm({...form,pdd_order_id:e.target.value})}/></div><select className="ios-input w-full rounded-xl px-4 py-3" value={form.task_type} onChange={e=>setForm({...form,task_type:e.target.value})}><option value="custom_message">人工消息</option><option value="restore_phone">恢复手机号</option><option value="change_phone">修改手机号</option><option value="urge_shipping">催发货</option><option value="logistics_question">物流询问</option></select><textarea className="ios-input min-h-36 w-full rounded-xl p-4" placeholder="最终发送正文 *" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div><div className="flex justify-end gap-3 border-t p-5"><button onClick={()=>setOpen(false)} className="rounded-xl bg-gray-100 px-5 py-2.5 font-bold">取消</button><button disabled={busy==='create'} onClick={create} className="rounded-xl bg-violet-600 px-5 py-2.5 font-bold text-white disabled:opacity-50">创建并预检</button></div></div></div>}
 </div>
};
export default PDDMessageWorkbench;
