-- +goose Up
CREATE TABLE pdd_collector_devices (id TEXT PRIMARY KEY,name TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,enabled INTEGER NOT NULL DEFAULT 1,last_seen_at BIGINT NOT NULL DEFAULT 0,last_collected_at BIGINT NOT NULL DEFAULT 0,created_at BIGINT NOT NULL);
CREATE TABLE pdd_products (id BIGSERIAL PRIMARY KEY,goods_id TEXT NOT NULL UNIQUE,final_url TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',images_json TEXT NOT NULL DEFAULT '[]',first_collected_at BIGINT NOT NULL,last_collected_at BIGINT NOT NULL);
CREATE TABLE pdd_skus (id BIGSERIAL PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES pdd_products(id) ON DELETE CASCADE,goods_id TEXT NOT NULL,sku_id TEXT NOT NULL,specs_json TEXT NOT NULL,spec_value_ids_json TEXT NOT NULL,thumb_url TEXT NOT NULL DEFAULT '',prices_json TEXT NOT NULL,price_cent BIGINT NOT NULL DEFAULT 0,stock BIGINT NOT NULL DEFAULT 0,is_onsale INTEGER NOT NULL DEFAULT 0,raw_snapshot_json TEXT NOT NULL,last_collected_at BIGINT NOT NULL,UNIQUE(goods_id,sku_id));
CREATE TABLE pdd_collection_snapshots (id BIGSERIAL PRIMARY KEY,collection_id TEXT NOT NULL UNIQUE,device_id TEXT NOT NULL REFERENCES pdd_collector_devices(id),product_id BIGINT NOT NULL REFERENCES pdd_products(id) ON DELETE CASCADE,goods_id TEXT NOT NULL,final_url TEXT NOT NULL,payload_json TEXT NOT NULL,collected_at BIGINT NOT NULL,received_at BIGINT NOT NULL);
CREATE TABLE pdd_sku_snapshots (id BIGSERIAL PRIMARY KEY,collection_snapshot_id BIGINT NOT NULL REFERENCES pdd_collection_snapshots(id) ON DELETE CASCADE,pdd_sku_id BIGINT NOT NULL REFERENCES pdd_skus(id) ON DELETE CASCADE,goods_id TEXT NOT NULL,sku_id TEXT NOT NULL,specs_json TEXT NOT NULL,spec_value_ids_json TEXT NOT NULL,thumb_url TEXT NOT NULL,prices_json TEXT NOT NULL,price_cent BIGINT NOT NULL DEFAULT 0,stock BIGINT NOT NULL DEFAULT 0,is_onsale INTEGER NOT NULL DEFAULT 0,raw_snapshot_json TEXT NOT NULL,collected_at BIGINT NOT NULL);
CREATE INDEX idx_pdd_skus_product ON pdd_skus(product_id);
CREATE INDEX idx_pdd_sku_snapshots_collection ON pdd_sku_snapshots(collection_snapshot_id);
-- +goose Down
DROP TABLE IF EXISTS pdd_sku_snapshots; DROP TABLE IF EXISTS pdd_collection_snapshots; DROP TABLE IF EXISTS pdd_skus; DROP TABLE IF EXISTS pdd_products; DROP TABLE IF EXISTS pdd_collector_devices;
